// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjJ-S2c3dVvfZaS8ZTcx-foOdXZU4xgZY',
    appId: '1:798662911029:web:01b8a9e371d0a63d11fd7c',
    messagingSenderId: '798662911029',
    projectId: 'linksaver-c56a9',
    authDomain: 'linksaver-c56a9.firebaseapp.com',
    storageBucket: 'linksaver-c56a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAGAVfzZH5L_0KTe9ux-zBoJGRSRfwnf0',
    appId: '1:798662911029:android:739c333fc9766ed011fd7c',
    messagingSenderId: '798662911029',
    projectId: 'linksaver-c56a9',
    storageBucket: 'linksaver-c56a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxQ5FoX5S9bioXUXgH6gWkChiTBhhw_4k',
    appId: '1:798662911029:ios:23d90591e7f3bd8911fd7c',
    messagingSenderId: '798662911029',
    projectId: 'linksaver-c56a9',
    storageBucket: 'linksaver-c56a9.firebasestorage.app',
    iosBundleId: 'com.example.linksaver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxQ5FoX5S9bioXUXgH6gWkChiTBhhw_4k',
    appId: '1:798662911029:ios:23d90591e7f3bd8911fd7c',
    messagingSenderId: '798662911029',
    projectId: 'linksaver-c56a9',
    storageBucket: 'linksaver-c56a9.firebasestorage.app',
    iosBundleId: 'com.example.linksaver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjJ-S2c3dVvfZaS8ZTcx-foOdXZU4xgZY',
    appId: '1:798662911029:web:769920c253e09c2c11fd7c',
    messagingSenderId: '798662911029',
    projectId: 'linksaver-c56a9',
    authDomain: 'linksaver-c56a9.firebaseapp.com',
    storageBucket: 'linksaver-c56a9.firebasestorage.app',
  );
}
